version: "3.8"

volumes:
  car_park_prod_postgres_data:
  car_park_prod_static_volume:


services:
  car_park_prod_web:
    container_name: car_park_prod_web_container
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    image: "${WEB_IMAGE}"
    command: bash -c "
      python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
      "
    volumes:
      - car_park_prod_static_volume:/web/static
    expose:
      - 8000
    env_file: ../backend/.env_files.prod/.env.prod.settings
    depends_on:
      - cara_park_prod_db

  car_park_prod_db:
    container_name: car_park_prod_db_container
    image: postgres
    volumes:
      - car_park_prod_postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - ../backend/.env_files.prod/.env.prod.db



  car_park_prod_nginx:
    container_name: car_park_prod_nginx_container
    build:
      context: ../nginx.prod
    image: "${NGINX_IMAGE}"
    volumes:
      - car_park_prod_static_volume:/web/static
    ports:
      - "80:80"
    depends_on:
      - nots_prod_web


